# Generated by Django 3.1 on 2020-08-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookbase_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookbase',
            options={'ordering': ['-id', '-timestamp']},
        ),
    ]
